name: ffi_interpop_c
description: This example shows how to combine Dart with other languages such as C ++, Pascal and others.
# version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.13.4 <3.0.0'

dependencies:
  path: ^1.7.0
  ffi: ^1.1.2
  dart_console: ^1.0.0

dev_dependencies:
  pedantic: ^1.9.0
  test: ^1.14.4
